<?php

return Symfony\CS\Config\Config::create()
    ->level(Symfony\CS\FixerInterface::PSR2_LEVEL)
    ->fixers([
        'psr0',
        'ordered_use',
        'unused_use',
        'remove_lines_between_uses',
        'remove_leading_slash_use',
        'phpdoc_no_empty_return',
        'phpdoc_params',
        'phpdoc_to_comment',
        'phpdoc_order',
        'short_array_syntax',
        'single_array_no_trailing_comma',
        'multiline_array_trailing_comma',
        'concat_with_spaces',
        'single_quote',
        'ternary_spaces',
        'operators_spaces',
        'empty_return',
        'new_with_braces',
    ])
    ->finder(
        Symfony\CS\Finder\DefaultFinder::create()
            ->in('src')
            ->in('test')
    );
